name: one_vpn
description: OneConnect_VPN
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-210.3.beta <4.0.0'

dependencies:
  oneconnect_flutter: ^1.0.1
  purchases_flutter: ^6.0.0
  app_tracking_transparency: ^2.0.4
  cached_network_image: ^3.3.0
  country_codes: ^2.2.0
  country_icons: ^2.0.2
  dart_ping: ^9.0.1
  dio: ^5.3.3
  easy_localization: ^3.0.3
  extended_tabs: ^4.1.0
  firebase_analytics: ^10.6.2
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  google_fonts: ^6.1.0
  google_mobile_ads: ^3.1.0
  in_app_update: ^4.2.2
  lottie: ^2.7.0
  ndialog: ^4.3.1

  package_info_plus: ^4.2.0
  provider: ^6.0.5
  pull_to_refresh_flutter3: ^2.0.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.5
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  file_picker: ^6.1.1
  image_cropper: ^5.0.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.15.3
  http: ^1.1.2
  crypto: ^3.0.3
  pin_code_fields: ^8.0.1
  flutter_fortune_wheel: ^1.3.0
  pin_input_text_field: ^4.5.1
  fluttertoast: ^8.2.4
  connectivity_plus: ^4.0.2
  share_plus: ^7.2.1
  flutter_inappwebview: ^5.8.0
  introduction_screen: ^3.1.12
  flutter_stripe: ^10.0.0
  pay: ^1.1.2

  #state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/logo_android.png"
  image_path_ios: "assets/icons/logo_ios.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/images/"
    - "assets/images/maps/"
    - "assets/icons/"
    - "assets/animations/"
    - "assets/languages/"

  fonts:
    - family: campton_bold
      fonts:
        - asset: assets/fonts/campton_bold.otf
